### ISSUE TITLE
Version Problem

### ISSUE THREAD

**Issue by cfransen** [nikhilbiju67/chat_input#1]
Any chance you could get this upgraded appropriately?

Because every version of chat_input depends on uuid ^3.0.1 and tagger_new depends on uuid ^4.2.2, chat_input is forbidden.
So, because tagger_new depends on chat_input any, version solving failed.

**Comment by stact** [comment]
You can use for the moment dependencies override to solve your issue

`pubspec.yaml`

```yaml
environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  uuid: "n.n.n" // the version you want to override, means it will use the version for all the packages using uuid even your dependencies
  p2: "13.0.1"
  p3: "1.2.2"
  [...]

dev_dependencies:
  px: ^9.0.0
  [...]

dependencies:
  chat_input: ^x.x.x
  py: ^5.1.1
  [...]
```
